name: Update parsers version
on:
  push:
    branches: [ main ]
    paths:
    - 'parsers/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name : GITHUB CONTEXT
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      #- name: Global
      #  run: |
      #    echo $GITHUB_WORKSPACE $GITHUB_REF $GITHUB_SHA ${{ github.event.before }} ${{ github.event.after }}
      - id: files
        name: Upload version to server
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            var_id=$(cat $GITHUB_WORKSPACE/$changed_file | grep -E '\"id\"\:\s*' | sed -r 's/\s*"id"\s*:\s*([0-9]+)\s*,?\s*/\1/g')
            var_version=$(cat $GITHUB_WORKSPACE/$changed_file | grep -E '\"version\"\:\s*' | sed -r 's/\s*"version"\s*:\s*([0-9]+)\s*,?\s*/\1/g')
            var_d=$(date +%u)
            curl -s "https://mw.lomikxp.ru/api/v1/repo/versions?set=$var_id&v=$var_version&k=${{ secrets.VERS_KEY }}$var_d"
          done
